version: "3"
services:
  code-camp-nginx:
    ports:
      - "80:80"
  code-camp-backend:
    build:
      context: .
      args:
        NODE_ENV: prod
    environment:
      - NODE_ENV=prod
      - MONGO_USER=grini
      - MONGO_PASSWORD=grini
      - REDIS_SECRET=secret
    command: npm start
